"""empty message

Revision ID: d8fcaf386f81
Revises: 
Create Date: 2021-09-06 15:04:43.158961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8fcaf386f81'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areas',
    sa.Column('area_code', sa.String(length=15), nullable=False),
    sa.Column('area_name', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('area_code', 'area_name')
    )
    op.create_table('restaurants',
    sa.Column('id', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('address', sa.String(length=50), nullable=True),
    sa.Column('url', sa.String(length=50), nullable=True),
    sa.Column('tel', sa.String(length=15), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('image1', sa.String(length=50), nullable=True),
    sa.Column('image2', sa.String(length=50), nullable=True),
    sa.Column('holiday', sa.String(length=30), nullable=True),
    sa.Column('category', sa.String(length=30), nullable=True),
    sa.Column('bottomless', sa.Boolean(), nullable=True),
    sa.Column('private_room', sa.Boolean(), nullable=True),
    sa.Column('area_code', sa.String(length=10), nullable=True),
    sa.Column('budget', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('restaurants')
    op.drop_table('areas')
    # ### end Alembic commands ###
